version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'gday'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'gday'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - dev-db:/var/lib/mysql
  redis-server:
    restart: always
    image: redis:4.0
    container_name: redis-server
    command: /bin/bash -c 'redis-server --appendonly yes --requirepass password'
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - '6380:6379'
    volumes:
      - ./redis:/data
# Names our volume
volumes:
  dev-db:
